// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kgokqchabjngurlcktzr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtnb2txY2hhYmpuZ3VybGNrdHpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1ODU2NjAsImV4cCI6MjA2MzE2MTY2MH0.ry_2OGbxScq_W5zPDg3EOLCiKYaVobGOp4YxUcxfObc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);